language: node_js

node_js:
  - "7.0"
  - "6.9"
  - "4.6"
  - "0.12"

env:
#  - CC=clang CXX=clang
  - CC=gcc-4.8 CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
#      - llvm-toolchain-precise-3.8
    packages:
      - gcc-4.8
      - g++-4.8
#      - clang-3.8
